

  
  const sampleState = [{
    reading_list_id: 1,
    user_id: 1,
    username: 'John',
    book_id: 1,
    title: 'ABCs',
    author: 'Mr A',
    genre_id: 1,
    genre: 'children',
    status_id: 1,
    status: 'current',
    recommend: null,
    review: null},
    {
      reading_list_id: 2,
    user_id: 1,
    username: 'John',
    book_id: 2,
    title: 'Cars',
    author: 'Auto Mechanic',
    genre_id: 2,
    genre: 'cars',
    status_id: 1,
    status: 'current',
    recommend: null,
    review: null},
    {
      reading_list_id: 3,
      user_id: 1,
      username: 'John',
      book_id: 3,
      title: 'Trees',
      author: 'McTree',
      genre_id: 3,
      genre: 'botany',
      status_id: 2,
      status: 'past',
      recommend: true,
      review: 'Very educational! I learned a lot of all the varieties of trees this planet has to offer! I highly recommend!!!'},
      {
        reading_list_id: 4,
        user_id: 1,
        username: 'John',
        book_id: 4,
        title: 'Cherry Blossom Trees',
        author: 'Sakura',
        genre_id: 3,
        genre: 'botany',
        status_id: 2,
        status: 'past',
        recommend: true,
        review: 'I learned alot about all the sajura varietals that exist and am inspired to make a trip to Washington DC to see the cherry blossoms bloom!'},
        {
          reading_list_id: 5,
          user_id: 1,
          username: 'John',
          book_id: 5,
          title: 'Calvin and Hobbes',
          author: 'Bill Watterson',
          genre_id: 4,
          genre: 'comics',
          status_id: 3,
          status: 'future',
          recommend: null,
          review: null},
          {
            reading_list_id: 6,
            user_id: 1,
            username: 'John',
            book_id: 6,
            title: 'Calvin and Hobbes Sunday Comics',
            author: 'Bill Watterson',
            genre_id: 4,
            genre: 'comics',
            status_id: 3,
            status: 'future',
            recommend: null,
            review: null},
            {
              reading_list_id: 7,
              user_id: 2,
              username: 'Carly',
              book_id: 7,
              title: 'West Coast',
              author: 'Beverly Cleary',
              genre_id: 5,
              genre: 'fiction',
              status_id: 1,
              status: 'current',
              recommend: null,
              review: null},
              {
                reading_list_id: 8,
                user_id: 3,
                username: 'Jonah',
                book_id: 8,
                title: 'East Coast',
                author: 'Johnson McJohnson',
                genre_id: 5,
                genre: 'fiction',
                status_id: 1,
                status: 'current',
                recommend: null,
                review: null},
                {
                  reading_list_id: 9,
                  user_id: 3,
                  username: 'Steve',
                  book_id: 9,
                  title: 'Archie Comics',
                  author: 'unknown',
                  genre_id: 4,
                  genre: 'comics',
                  status_id: 2,
                  status: 'past',
                  recommend: true,
                  review: 'I recommend Archie Comics for anyone interested in more old school comics.'},
                  {
                    reading_list_id: 10,
                    username: 'Steve',
                    book_id: 10,
                    title: 'Archie Comics Part 2',
                    author: 'unknown',
                    genre_id: 4,
                    genre: 'comics',
                    status_id: 2,
                    status: 'past',
                    recommend: false,
                    review: 'Archie Comics Part 2 definitely was not as amazing as part 1, i definitely would not recommend at all.'},
                    {
                      reading_list_id: 11,
                      user_id: 4,
                      username: 'Eve',
                      book_id: 11,
                      title: 'Peanuts Vol 1',
                      author: 'Charles M Schulz',
                      genre_id: 4,
                      genre: 'comics',
                      status_id: 3,
                      status: 'future',
                      recommend: null,
                      review: null},
                      {
                      reading_list_id: 12,
                      user_id: 4,
                      username: 'Eve',
                      book_id: 12,
                      title: 'Peanuts Vol 1',
                      author: 'Charles M Schulz',
                      genre_id: 4,
                      genre: 'comics',
                      status_id: 3,
                      status: 'future',
                      recommend: null,
                      review: null}
  
  ];

  export default sampleState;